name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install brew
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - name: Add environment
        run: eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
      - name: Install trunk
        run: brew install trunk
      - name: Build
        run: trunk build